import { Transform } from 'stream'

export class ReplaceStream extends Transform {
  constructor (searchStr, replaceStr, options) {
    super({ ...options })
    this.searchStr = searchStr
    this.replaceStr = replaceStr
    this.tail = ''
  }

  _transform (chunk, encoding, callback) {
    const pieces = (this.tail + chunk).split(this.searchStr)
    const lastPiece = pieces[pieces.length - 1]
    const tailLen = this.searchStr.length - 1
    this.tail = lastPiece.slice(-tailLen)
    pieces[pieces.length - 1] = lastPiece.slice(0, -tailLen)

    this.push(pieces.join(this.replaceStr))
    callback()
  }

  _flush (callback) {
    this.push(this.tail)
    callback()
  }
}

// Our algorithm splits the data in memory (tail data and the current chunk)
// using searchStr as a separator.
// 2. Then, it takes the last item of the array generated by the operation and
// extracts the last searchString.length - 1 characters. The result is saved
// in the tail variable and will be prepended to the next chunk of data.
// 3. Finally, all the pieces resulting from split() are joined together using
// replaceStr as a separator and pushed into the internal buffer.